### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by baesik** [darkfiggy/dmaxplugin#3]
Hi there! I'd love to use this plugin and thank you for your previous work on it.

I'm getting this error when I try to click any option of the plugin:

```
Exception Details:
System.MissingFieldException: Field not found: 'PKHeX.Core.SaveFile.FileName'.
   at DynamaxAdventureReset.DynamaxAdventureReset.mainBTN_Click(Object sender, EventArgs e)
   at DynamaxAdventureReset.DynamaxAdventureReset.<AddPluginControl>b__14_0(Object s, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
<snip>
--------------------
User Message:
An unhandled exception has occurred.
You can continue running PKHeX, but please report this error.
```

Following this error, no dialog box appears to edit any adventure raids.

Edit: Using the latest PKHex version as of this date, which is 20210406.

**Comment by ReshiQuori** [comment]
Should be fixed with the latest revision I just pushed.
